/*
"８６ ",
"ｂＢ ",
"Ｃ－ＨＲ ",
"ＦＪクルーザー ",
"ｉＱ ",
"ＭＲ２ ",
"ＭＲ－Ｓ ",
"ＳＡＩ ",
"ＷｉＬＬ　サイファ ",
"アクア ",
"アバロン ",
"アベンシスセダン ",
"アベンシスワゴン ",
"アリオン ",
"アリスト ",
"アルテッツァ ",
"アルファード ",
"アルファードＧ ",
"アルファードＶ ",
"アルファードハイブリッド ",
"アレックス ",
"イスト ",
"イプサム ",
"ヴァンガード ",
"ウィンダム ",
"ヴェルファイア ",
"ｳﾞｪﾙﾌｧｲｱﾊｲﾌﾞﾘｯﾄﾞ ",
"ヴェロッサ ",
"ヴォクシー ",
"エスクァイア ",
"エスティマ ",
"エスティマ・ルシーダ ",
"エスティマＬ ",
"エスティマＴ ",
"エスティマハイブリッド ",
"オーパ ",
"オリジン ",
"ガイア ",
"カムリ ",
"カムリグラシアセダン ",
"カリーナ ",
"カルディナ ",
"カルディナバン ",
"カローラ ",
"カローラスパシオ ",
"カローラツーリングワゴン ",
"カローラバン ",
"カローラランクス ",
"カローラルミオン ",
"カローラレビン ",
"キャミ ",
"クラウン ",
"ｸﾗｳﾝ･ｽﾃｰｼｮﾝﾜｺﾞﾝ ",
"クラウンエステート ",
"クラウンセダン ",
"クラウンハイブリッド ",
"クラウンバン ",
"クラウンマジェスタ ",
"グランドハイエース ",
"グランビア ",
"クルーガー ",
"クルーガーＬ ",
"クルーガーＶ ",
"クルーガーハイブリッド ",
"クレスタ ",
"コースター ",
"コルサ ",
"コロナ ",
"コロナプレミオ ",
"スープラ ",
"スターレット ",
"スパーキー ",
"スプリンター ",
"スプリンタートレノ ",
"スプリンターバン ",
"スペイド ",
"セラ ",
"セリカ ",
"セリカＸＸ ",
"セルシオ ",
"センチュリー ",
"ソアラ ",
"ターセル ",
"ダイナアーバンサポーター ",
"ダイナトラック ",
"ダイナルートバン ",
"タウンエーストラック ",
"タウンエースノア ",
"タウンエースバン ",
"タンク ",
"チェイサー ",
"ツーリングハイエース ",
"トヨエース ",
"ﾄﾖｴｰｽｱｰﾊﾞﾝｻﾎﾟｰﾀ ",
"トヨタ　その他 ",
"ナディア ",
"ノア ",
"ハイエースコミューター ",
"ハイエーストラック ",
"ハイエースバン ",
"ハイエースワゴン ",
"ハイラックス ",
"ハイラックスサーフ ",
"ﾊｲﾗｯｸｽｽﾎﾟｰﾂﾋﾟｯｸｱｯﾌﾟ ",
"パッソセッテ ",
"ハリアー ",
"ハリアーハイブリッド ",
"ピクシスエポック ",
"ピクシスジョイ ",
"ピクシススペース ",
"ピクシストラック ",
"ピクシスバン ",
"ピクシスメガ ",
"ビスタアルデオ ",
"ファンカーゴ ",
"プラッツ ",
"プリウス ",
"プリウスＰＨＶ ",
"プリウスα ",
"ブレイド ",
"ブレビス ",
"プレミオ ",
"プログレ ",
"マークＩＩ ",
"マークＩＩクオリス ",
"マークＩＩバン ",
"マークＩＩブリット ",
"マークＩＩワゴン ",
"マークＸジオ ",
"ライトエーストラック ",
"ライトエースノア ",
"ライトエースバン ",
"ラッシュ ",
"ランドクルーザー ",
"ランドクルーザー１００ ",
"ランドクルーザー６０ ",
"ランドクルーザー７０ ",
"ランドクルーザー８０ ",
"ランドクルーザープラド ",
"ルーミー ",
"レジアス ",
"レジアス（ハイエース） ",
"レジアスエースバン ",
"１８０ＳＸ ",
"ｅ－ＮＶ２００バン ",
"ｅ－ＮＶ２００ワゴン ",
"ＧＴ－Ｒ ",
"NT100ｸﾘｯﾊﾟｰﾄﾗｯｸ ",
"ＮＶ１００クリッパーバン ",
"ＮＶ１００クリッパーリオ ",
"ＮＶ２００バネットバン ",
"ＮＶ２００バネットワゴン ",
"ＮＶ３５０キャラバンバン ",
"NV350ｷｬﾗﾊﾞﾝﾏｲｸﾛﾊﾞｽ ",
"NV350ｷｬﾗﾊﾞﾝﾜｺﾞﾝ ",
"アトラストラック ",
"アベニール ",
"アベニールカーゴ ",
"インフィニティＱ４５ ",
"エキスパート ",
"エクストレイル ",
"エルグランド ",
"オッティ ",
"キックス ",
"キャラバン ",
"キャラバンコーチ ",
"キャラバンバス ",
"キャラバンマイクロバス ",
"キューブ ",
"キューブキュービック ",
"クリッパートラック ",
"クリッパーバン ",
"クリッパーリオ ",
"グロリア ",
"グロリアワゴン ",
"サニー ",
"サニーＲＺ－１ ",
"サニートラック ",
"サファリ ",
"シーマ ",
"シビリアンバス ",
"ジューク ",
"シルビア ",
"シルフィ ",
"スカイライン ",
"ｽｶｲﾗｲﾝｸﾛｽｵｰﾊﾞｰ ",
"ステージア ",
"セドリック ",
"セフィーロ ",
"ダットサントラック ",
"ダットサンピックアップ ",
"チェリー ",
"ティアナ ",
"ティーダ ",
"ティーノ ",
"デイズ ",
"デイズルークス ",
"デュアリス ",
"テラノ ",
"テラノレグラス ",
"パオ ",
"バサラ ",
"バネットセレナ ",
"バネットトラック ",
"バネットバン ",
"パルサー ",
"ピノ ",
"フィガロ ",
"フーガ ",
"フーガハイブリッド ",
"フェアレディＺ ",
"プリメーラ ",
"プリメーラワゴン ",
"ブルーバード ",
"ブルーバードシルフィ ",
"プレサージュ ",
"プレジデント ",
"プレジデントＪＳ ",
"プレセア ",
"マーチ ",
"マイクラＣ＋Ｃ ",
"ムラーノ ",
"モコ ",
"ラシーン ",
"ラティオ ",
"ラフェスタ ",
"ラルゴ ",
"リーフ ",
"リバティ ",
"ルークス ",
"ルネッサ ",
"レパード ",
"ローレル ",
"ＣＲ－Ｖ ",
"ＣＲ－Ｘ ",
"ＣＲ－Ｚ ",
"Ｎ　ＢＯＸ ",
"Ｎ　ＢＯＸ＋ ",
"Ｎ　ＢＯＸ＋カスタム ",
"Ｎ　ＢＯＸカスタム ",
"Ｎ－ＢＯＸスラッシュ ",
"Ｎ－ＯＮＥ ",
"ＮＳＸ ",
"Ｎ－ＷＧＮ ",
"Ｎ－ＷＧＮカスタム ",
"Ｓ２０００ ",
"Ｓ６６０ ",
"Ｓ－ＭＸ ",
"Ｚ ",
"アヴァンシア ",
"アクティトラック ",
"アクティバン ",
"アコード ",
"アコードクーペ ",
"アコードツアラー ",
"アコードハイブリッド ",
"アコードワゴン ",
"アスコット ",
"インスパイア ",
"インテグラ ",
"ヴェゼル ",
"エアウェイブ ",
"エディックス ",
"エリシオン ",
"エリシオンプレステージ ",
"オデッセイ ",
"オデッセイハイブリッド ",
"オルティア ",
"キャパ ",
"グレイス ",
"クロスロード ",
"ザッツ ",
"ジェイド ",
"シティ ",
"シビック ",
"シビッククーペ ",
"シビックフェリオ ",
"シャトル ",
"ステップワゴン ",
"ステップワゴンスパーダ ",
"ストリート ",
"セイバー ",
"ゼスト ",
"ゼストスパーク ",
"トゥデイ ",
"トルネオ ",
"バモス ",
"バモスホビオ ",
"バモスホビオプロ ",
"ビート ",
"フィットアリア ",
"フィットシャトル ",
"ﾌｨｯﾄｼｬﾄﾙﾊｲﾌﾞﾘｯﾄﾞ ",
"フィットハイブリッド ",
"フリード ",
"フリード＋ハイブリッド ",
"フリードスパイク ",
"ﾌﾘｰﾄﾞｽﾊﾟｲｸﾊｲﾌﾞﾘｯﾄﾞ ",
"フリードハイブリッド ",
"モビリオ ",
"モビリオスパイク ",
"ライフ ",
"ラグレイト ",
"レジェンド ",
"レジェンドクーペ ",
"ロゴ ",
"ＡＺオフロード ",
"ＡＺワゴン ",
"AZﾜｺﾞﾝｶｽﾀﾑｽﾀｲﾙ ",
"ＣＸ－３ ",
"ＣＸ－５ ",
"ＣＸ－７ ",
"ＭＰＶ ",
"ＲＸ－７ ",
"ＲＸ－７（アンフィニ） ",
"ＲＸ－７（サバンナ） ",
"ＲＸ－８ ",
"アクセラハイブリッド ",
"アテンザスポーツ ",
"アテンザスポーツワゴン ",
"アテンザセダン ",
"アテンザワゴン ",
"オートザムＡＺ－１ ",
"カペラ ",
"キャロル ",
"キャロルエコ ",
"スクラム ",
"スクラムトラック ",
"スクラムワゴン ",
"スピアーノ ",
"タイタンダッシュ ",
"タイタントラック ",
"トリビュート ",
"ビアンテ ",
"ファミリアバン ",
"フレア ",
"フレアカスタムスタイル ",
"フレアクロスオーバー ",
"ﾌﾚｱﾜｺﾞﾝｶｽﾀﾑｽﾀｲﾙ ",
"プレマシー ",
"ブローニィトラック ",
"ブローニィバン ",
"ベリーサ ",
"ボンゴトラック ",
"ボンゴバン ",
"ボンゴフレンディ ",
"マツダスピードアクセラ ",
"マツダスピードアテンザ ",
"ミレーニア ",
"ラピュタ ",
"ロードスター ",
"３６０ ",
"ＢＲＺ ",
"Ｒ２ ",
"ＷＲＸ　Ｓ４ ",
"ＷＲＸ　ＳＴＩ ",
"アウトバック ",
"インプレッサＧ４ ",
"インプレッサＷＲＸ ",
"インプレッサＸＶ ",
"ｲﾝﾌﾟﾚｯｻXVﾊｲﾌﾞﾘｯﾄﾞ ",
"インプレッサアネシス ",
"インプレッサスポーツ ",
"ｲﾝﾌﾟﾚｯｻｽﾎﾟｰﾂﾊｲﾌﾞﾘｯﾄﾞ ",
"ｲﾝﾌﾟﾚｯｻｽﾎﾟｰﾂﾜｺﾞﾝ ",
"ヴィヴィオビストロ ",
"エクシーガ ",
"サンバーディアス ",
"サンバートラック ",
"サンバーバン ",
"ステラ ",
"ディアスワゴン ",
"トラヴィック ",
"トレジア ",
"フォレスター ",
"プレオ ",
"プレオプラス ",
"ルクラ ",
"レヴォーグ ",
"レガシィＢ４ ",
"レガシィツーリングワゴン ",
"レガシィランカスター "
"ＲＡＶ４ ",
"ＲＡＶ４　Ｊ ",
"ＲＡＶ４　Ｌ ",

*/



///////////////////////////////////////////////
var preselect_makers = ["	LEXUS 	",
"	TOYOTA 	",
"	NISSAN 	",
"	HONDA 	",
"	MITSUBISHI 	",
"	MAZDA 	",
"	EUNOS 	",
"	FORD JAPAN 	",
"	SUBARU 	",
"	DAIHATSU 	",
"	SUZUKI 	",
"	ISUZU 	",
"	HINO 	",
"	MITSUOKA 	",
"	MITSUBISHI FUSO 	",
"	NISSAN DIESEL 	",
"	CADILLAC 	",
"	CHEVROLET 	",
"	GMC 	",
"	BUICK 	",
"	HUMMER 	",
"	LINCOLN 	",
"	FORD 	",
"	CHRYSLER 	",
"	CHRYSLER JEEP 	",
"	DODGE 	",
"	PLYMOUTH 	",
"	WINNEBAGO 	",
"	LEXUS 	",
"	INFINITI 	",
"	ACURA 	",
"	AMERICA TOYOTA 	",
"	AMERICA NISSAN 	",
"	AMERICA HONDA 	",
"	AMERICA SUBARU 	",
"	MERCEDES BENZ 	",
"	AMG 	",
"	MAYBACH 	",
"	MCC SMART 	",
"	BMW 	",
"	BMW ALPINA 	",
"	AUDI 	",
"	VOLKSWAGEN 	",
"	OPEL 	",
"	PORSCHE 	",
"	EUROPE FORD 	",
"	ARTEGA 	",
"	MERCEDES MAYBACH 	",
"	MERCEDES AMG 	",
"	BENTLEY 	",
"	JAGUAR 	",
"	DAIMLER 	",
"	LAND ROVER 	",
"	MG 	",
"	MINI 	",
"	ROVER 	",
"	LOTUS 	",
"	ASTON MARTIN 	",
"	TVR 	",
"	FIAT 	",
"	FERRARI 	",
"	LANCIA 	",
"	ALFA ROMEO 	",
"	MASERATI 	",
"	LAMBORGHINI 	",
"	ABARTH 	",
"	RENAULT 	",
"	PEUGEOT 	",
"	CITROEN 	",
"	VOLVO 	",
"	SAAB 	",
"	HYUNDAI 	"];


var preselect_models = {
"LEXUS":	[		
"	CT 	",	
"	GS 	",	
"	GS F 	",	
"	HS 	",	
"	IS 	",	
"	IS F 	",	
"	LC 	",	
"	LS 	",	
"	LX 	",	
"	NX 	",	
"	RC 	",	
"	RC F 	",	
"	RX 	",	
"	SC 	"	],
"TOYOTA":	[		
"	86 	",	
"	ALLEX 	",	
"	ALLION 	",	
"	ALPHARD 	",	
"	ALPHARD G 	",	
"	ALPHARD HYBRID 	",	
"	ALPHARD V 	",	
"	ALTEZZA 	",	
"	ALTEZZA GITA 	",	
"	AQUA 	",	
"	ARISTO 	",	
"	AURIS 	",	
"	AVALON 	",	
"	AVENSIS SEDAN 	",	
"	AVEVSIS WAGON 	",	
"	bB 	",	
"	BELTA 	",	
"	BLADE 	",	
"	BREVIS 	",	
"	CALDINA 	",	
"	CALDINA VAN 	",	
"	CAMI 	",	
"	CAMROAD 	",	
"	CAMRY 	",	
"	CAMRY GRACIA 	",	
"	CAMRY GRACIA STATIONWAGON 	",	
"	CARINA 	",	
"	CELICA 	",	
"	CELSIOR 	",	
"	CENTURY 	",	
"	CHASER 	",	
"	C-HR 	",	
"	COASTER 	",	
"	COASTER BIG VAN 	",	
"	COMFORT 	",	
"	COROLLA 	",	
"	COROLLA AXIO 	",	
"	COROLLA CERES 	",	
"	COROLLA FIELDER 	",	
"	COROLLA II 	",	
"	COROLLA LEVIN 	",	
"	COROLLA RUMION 	",	
"	COROLLA RUNX 	",	
"	COROLLA SPACIO 	",	
"	COROLLA TOURING WAGON 	",	
"	COROLLA VAN 	",	
"	CORONA 	",	
"	CORONA PREMIO 	",	
"	CORONA VAN 	",	
"	CRESTA 	",	
"	CROWN 	",	
"	CROWN COMFORT 	",	
"	CROWN ESTATE 	",	
"	CROWN HYBRID 	",	
"	CROWN MAJESTA 	",	
"	CROWN SEDAN 	",	
"	CROWN STATIONWAGON 	",	
"	CROWN VAN 	",	
"	DUET 	",	
"	DYNA ROUTE VAN 	",	
"	DYNA TRUCK 	",	
"	ESQUIRE 	",	
"	ESTIMA 	",	
"	ESTIMA EMINA 	",	
"	ESTIMA HYBRID 	",	
"	ESTIMA L 	",	
"	ESTIMA LUCIDA 	",	
"	ESTIMA T 	",	
"	FJ CRUISER 	",	
"	FUNCARGO 	",	
"	GAIA 	",	
"	GRAND HIACE 	",	
"	GRANVIA 	",	
"	HARRIER 	",	
"	HARRIER HYBRID 	",	
"	HIACE COMMUTER 	",	
"	HIACE REGIUS 	",	
"	HIACE TRUCK 	",	
"	HIACE VAN 	",	
"	HIACE WAGON 	",	
"	HILUX 	",	
"	HILUX PICK UP 	",	
"	HILUX SPORTS PICK UP 	",	
"	HILUX SURF 	",	
"	IPSUM 	",	
"	IQ 	",	
"	ISIS 	",	
"	IST 	",	
"	KLUGER 	",	
"	KLUGER HYBRID 	",	
"	KLUGER L 	",	
"	KLUGER V 	",	
"	LAND CRUISER 	",	
"	LAND CRUISER 100 	",	
"	LAND CRUISER 40 	",	
"	LAND CRUISER 60 	",	
"	LAND CRUISER 70 	",	
"	LAND CRUISER 80 	",	
"	LAND CRUISER PRADO 	",	
"	LITEACE NOAH 	",	
"	LITEACE TRUCK 	",	
"	LITEACE VAN 	",	
"	LITEACE WAGON 	",	
"	MARK II 	",	
"	MARK X 	",	
"	MARK X ZIO 	",	
"	MARKII BLIT 	",	
"	MARKII QUALIS 	",	
"	MARKII WAGON 	",	
"	MR2 	",	
"	MR-S 	",	
"	NADIA 	",	
"	NOAH 	",	
"	OPA 	",	
"	PASSO 	",	
"	PASSO SETTE 	",	
"	PIXIS EPOCH 	",	
"	PIXIS JOY 	",	
"	PIXIS MEGA 	",	
"	PIXIS SPACE 	",	
"	PIXIS TRUCK 	",	
"	PIXIS VAN 	",	
"	PLATZ 	",	
"	PORTE 	",	
"	PREMIO 	",	
"	PRIUS 	",	
"	PRIUS ALPHA 	",	
"	PRIUS PHV 	",	
"	PROBOX 	",	
"	PROBOX VAN 	",	
"	PROBOX WAGON 	",	
"	PROGRES 	",	
"	QUICK DELIVERY 	",	
"	RACTIS 	",	
"	RAUM 	",	
"	RAV4 	",	
"	RAV4J 	",	
"	RAV4L 	",	
"	REGIUS 	",	
"	REGIUS ACE VAN 	",	
"	ROOMY 	",	
"	RUSH 	",	
"	SAI 	",	
"	SIENTA 	",	
"	SOARER 	",	
"	SPADE 	",	
"	SPARKY 	",	
"	SPRINTER 	",	
"	SPRINTER CARIB 	",	
"	SPRINTER MARINO 	",	
"	SPRINTER WAGON 	",	
"	STARLET 	",	
"	SUCCEED 	",	
"	SUCCEED VAN 	",	
"	SUCCEED WAGON 	",	
"	SUPRA 	",	
"	TANK 	",	
"	TERCEL 	",	
"	TOURING HIACE 	",	
"	TOWNACE NOAH 	",	
"	TOWNACE TRUCK 	",	
"	TOWNACE VAN 	",	
"	TOWNACE WAGON 	",	
"	TOYOACE 	",	
"	TOYOACE ROUTE VAN 	",	
"	TOYOTA OTHER 	",	
"	VANGUARD 	",	
"	VELLFIRE 	",	
"	VELLFIRE HYBRID 	",	
"	VEROSSA 	",	
"	VISTA 	",	
"	VISTA ARDEO 	",	
"	VITZ 	",	
"	VOLTZ 	",	
"	VOXY 	",	
"	WILL CYPHA 	",	
"	WILL VI 	",	
"	WILL VS 	",	
"	WINDOM 	",	
"	WISH 	"	],
"NISSAN":	[		
"	180SX 	",	
"	AD 	",	
"	AD EXPERT 	",	
"	AD VAN 	",	
"	ATLAS TRUCK 	",	
"	AVENIR 	",	
"	AVENIR CARGO 	",	
"	BASSARA 	",	
"	BLUEBIRD 	",	
"	BLUEBIRD SYLPHY 	",	
"	CARAVAN 	",	
"	CARAVAN BUS 	",	
"	CARAVAN COACH 	",	
"	CARAVAN ELGRAND 	",	
"	CARAVAN MICROBUS 	",	
"	CEDRIC 	",	
"	CEDRIC VAN 	",	
"	CEFIRO 	",	
"	CHERRY 	",	
"	CIMA 	",	
"	CIVILIAN BUS 	",	
"	CLIPPER RIO 	",	
"	CLIPPER TRUCK 	",	
"	CLIPPER VAN 	",	
"	CUBE 	",	
"	CUBE CUBIC 	",	
"	DATSUN 	",	
"	DATSUN PICK UP 	",	
"	DATSUN TRUCK 	",	
"	DAYZ 	",	
"	DAYZ ROOX 	",	
"	DUALIS 	",	
"	ELGRAND 	",	
"	E-NV200VAN 	",	
"	EXPERT 	",	
"	FAIRLADY Z 	",	
"	FIGARO 	",	
"	FUGA 	",	
"	FUGA HYBRID 	",	
"	GLORIA 	",	
"	GLORIA WAGON 	",	
"	GT-R 	",	
"	HOMY ELGRAND 	",	
"	HOMY VAN 	",	
"	JUKE 	",	
"	KIX 	",	
"	LAFESTA 	",	
"	LARGO 	",	
"	LATIO 	",	
"	LAUREL 	",	
"	LEAF 	",	
"	LEOPARD 	",	
"	LIBERTY 	",	
"	MARCH 	",	
"	MARCH BOX 	",	
"	MICRA C+C 	",	
"	MOCO 	",	
"	MURANO 	",	
"	NOTE 	",	
"	NT100CLIPPER TRUCK 	",	
"	NT450 ATLAS 	",	
"	NV100CLIPPER RIO 	",	
"	NV100CLIPPER VAN 	",	
"	NV150AD 	",	
"	NV200 VANETTE VAN 	",	
"	NV200VANETTE WAGON 	",	
"	NV350CARAVAN VAN 	",	
"	NV350CARAVAN WAGON 	",	
"	OTTI 	",	
"	PAO 	",	
"	PINO 	",	
"	PRAIRIE JOY 	",	
"	PRESAGE 	",	
"	PRESIDENT 	",	
"	PRESIDENT JS 	",	
"	PRIMERA 	",	
"	PRIMERA WAGON 	",	
"	PULSAR SERIE 	",	
"	RASHEEN 	",	
"	ROOX 	",	
"	SAFARI 	",	
"	SERENA 	",	
"	SILVIA 	",	
"	SKYLINE 	",	
"	SKYLINE CROSSOVER 	",	
"	STAGEA 	",	
"	SUNNY 	",	
"	SUNNY TRUCK 	",	
"	SYLPHY 	",	
"	TEANA 	",	
"	TERRANO 	",	
"	TERRANO REGULUS 	",	
"	TIIDA 	",	
"	TIIDA LATIO 	",	
"	TINO 	",	
"	VANETTE TRUCK 	",	
"	VANETTE VAN 	",	
"	WINGROAD 	",	
"	X-TRAIL 	"	],
"HONDA":	[		
"	1300 	",	
"	145 	",	
"	ACCORD 	",	
"	ACCORD HYBRID 	",	
"	ACCORD TOURER 	",	
"	ACCORD WAGON 	",	
"	ACTY TRUCK 	",	
"	ACTY VAN 	",	
"	AIRWAVE 	",	
"	ASCOT 	",	
"	AVANCIER 	",	
"	BEAT 	",	
"	CAPA 	",	
"	CIVIC 	",	
"	CIVIC FERIO 	",	
"	CIVIC HYBRID 	",	
"	CROSS ROAD 	",	
"	CR-V 	",	
"	CR-X 	",	
"	CR-X DELSOL 	",	
"	CR-Z 	",	
"	EDIX 	",	
"	ELEMENT 	",	
"	ELYSION 	",	
"	ELYSION PRESTIGE 	",	
"	FIT 	",	
"	FIT ARIA 	",	
"	FIT HYBRID 	",	
"	FIT SHUTTLE 	",	
"	FIT SHUTTLE HYBRID 	",	
"	FREED 	",	
"	FREED HYBRID 	",	
"	FREED PLUS HYBRID 	",	
"	FREED SPIKE 	",	
"	FREED SPIKE HYBRID 	",	
"	GRACE 	",	
"	HR-V 	",	
"	INSIGHT 	",	
"	INSIGHT EXCLUSIVE 	",	
"	INSPIRE 	",	
"	INTEGRA 	",	
"	JADE 	",	
"	LAGREAT 	",	
"	LEGEND 	",	
"	LIFE 	",	
"	LIFE DUNK 	",	
"	LOGO 	",	
"	MDX 	",	
"	MOBILIO 	",	
"	MOBILIO SPIKE 	",	
"	N BOX 	",	
"	N BOX CUSTOM 	",	
"	N BOX PLUS 	",	
"	N BOX PLUS CUSTOM 	",	
"	N-BOX SLASH 	",	
"	N-ONE 	",	
"	NSX 	",	
"	N-WGN 	",	
"	N-WGN CUSTOM 	",	
"	ODYSSEY 	",	
"	ODYSSEY HYBRID 	",	
"	ODYSSEY PRESTIGE 	",	
"	ORTHIA 	",	
"	PERTNER 	",	
"	PRELUDE 	",	
"	S2000 	",	
"	S660 	",	
"	SHUTTLE 	",	
"	S-MX 	",	
"	STEPWAGON 	",	
"	STEPWAGON SPADA 	",	
"	STREAM 	",	
"	THAT’S 	",	
"	TODAY 	",	
"	TORNEO 	",	
"	VAMOS 	",	
"	VAMOS HOBIO 	",	
"	VAMOS HOBIO PRO 	",	
"	VEZEL 	",	
"	VIGOR 	",	
"	Z 	",	
"	ZEST 	",	
"	ZEST SPARK 	"	],
"MITSUBISHI":	[		
"	AIRTREK 	",	
"	ASPIRE 	",	
"	CHARIOT GRANDIS 	",	
"	COLT 	",	
"	COLT PLUS 	",	
"	DELICA CARGO 	",	
"	DELICA D:2 	",	
"	DELICA D:3 	",	
"	DELICA D:5 	",	
"	DELICA SPACE GEAR 	",	
"	DELICA STAR WAGON 	",	
"	DELICA TRUCK 	",	
"	DELICA VAN 	",	
"	DIAMANTE 	",	
"	DINGO 	",	
"	DION 	",	
"	EK CUSTOM 	",	
"	EK SPACE 	",	
"	EK SPACE CUSTOM 	",	
"	EK SPORT 	",	
"	EK WAGON 	",	
"	GALANT 	",	
"	GALANT FORTIS 	",	
"	GALANT FORTIS SPORT BACK 	",	
"	GRANDIS 	",	
"	GTO 	",	
"	I 	",	
"	I-MIEV 	",	
"	JEEP 	",	
"	LANCER 	",	
"	LANCER CARGO 	",	
"	LANCER CEDIA 	",	
"	LANCER CEDIA WAGON 	",	
"	LANCER WAGON 	",	
"	LEGNUM 	",	
"	LIBERO 	",	
"	MINICA 	",	
"	MINICAB TRUCK 	",	
"	MINICAB VAN 	",	
"	MINICAB-MIEV 	",	
"	MIRAGE 	",	
"	MITSUBISHI OTHER 	",	
"	OUTLANDER 	",	
"	OUTLANDER PHEV 	",	
"	PAJERO 	",	
"	PAJERO IO 	",	
"	PAJERO JR 	",	
"	PAJERO MINI 	",	
"	PROUDIA 	",	
"	RVR 	",	
"	TOPPO 	",	
"	TOPPO BJ 	",	
"	TOWN BOX 	",	
"	TRITON 	"	],
"MAZDA":	[		
"	ATENZA SEDAN 	",	
"	ATENZA SPORT 	",	
"	ATENZA SPORT WAGON 	",	
"	ATENZA WAGON 	",	
"	AUTOZAM AZ-1 	",	
"	AXELA 	",	
"	AXELA HYBRID 	",	
"	AXELA SPORT 	",	
"	AZ-OFFROAD 	",	
"	AZ-WAGON 	",	
"	AZ-WAGON CUSTOM STYLE 	",	
"	BIANTE 	",	
"	BONGO FRIENDEE 	",	
"	BONGO TRUCK 	",	
"	BONGO VAN 	",	
"	BRAWNY TRUCK 	",	
"	BRAWNY VAN 	",	
"	CAPELLA 	",	
"	CAPELLA WAGON 	",	
"	CAROL 	",	
"	CAROL ECO 	",	
"	CX-3 	",	
"	CX-5 	",	
"	CX-7 	",	
"	DEMIO 	",	
"	EFINI RX-7 	",	
"	FAMILIA 	",	
"	FAMILIA S-WAGON 	",	
"	FAMILIA VAN 	",	
"	FLAIR 	",	
"	FLAIR CROSSOVER 	",	
"	FLAIR CUSTOM STYLE 	",	
"	FLAIR WAGON 	",	
"	FLAIR WAGON CUSTOM STYEL 	",	
"	LANTIS 	",	
"	LUCE 	",	
"	MAZDA OTHER 	",	
"	MAZDA SPEED AXELA 	",	
"	MILLENIA 	",	
"	MPV 	",	
"	PORTER CAB 	",	
"	PREMACY 	",	
"	PROCEED 	",	
"	PROCEED LEVANTE 	",	
"	PROCEED MARVIE 	",	
"	ROADSTER 	",	
"	ROADSTER RF 	",	
"	RX-7 	",	
"	RX-8 	",	
"	SAVANNA RX-7 	",	
"	SCRUM 	",	
"	SCRUM TRUCK 	",	
"	SCRUM WAGON 	",	
"	SPIANO 	",	
"	TITAN DASH 	",	
"	TITAN TRUCK 	",	
"	TRIBUTE 	",	
"	VERISA 	"	],
"EUNOS":	[		
"	EUNOS ROADSTER 	",	
"	EUNOS500 	"	],
"FORD JAPAN":	[		
"	FESTIVA 	",	
"	FESTIVA MINIWAGON 	",	
"	FREDA 	",	
"	TELSTAR SEDAN 	"	],
"SUBARU":	[		
"	360 	",	
"	BRZ 	",	
"	CHIFFON 	",	
"	DEX 	",	
"	DIAS WAGON 	",	
"	EXIGA 	",	
"	EXIGA CROSSOVER7 	",	
"	FORESTER 	",	
"	IMPREZA 	",	
"	IMPREZA ANESIS 	",	
"	IMPREZA G4 	",	
"	IMPREZA SPORTS 	",	
"	IMPREZA SPORTS HYBRID 	",	
"	IMPREZA SPORTS WAGON 	",	
"	IMPREZA WRX 	",	
"	IMPREZA XV 	",	
"	IMPREZA XV HYBRID 	",	
"	JUSTY 	",	
"	LEGACY 	",	
"	LEGACY B4 	",	
"	LEGACY LANCASTER 	",	
"	LEGACY TOURING WAGON 	",	
"	LEVORG 	",	
"	LUCRA 	",	
"	LUCRA CUSTOM 	",	
"	OUTBACK 	",	
"	PLEO 	",	
"	PLEO NESTA 	",	
"	PLEO PLUS 	",	
"	R1 	",	
"	R2 	",	
"	SAMBAR DIAS 	",	
"	SAMBAR TRUCK 	",	
"	SAMBAR VAN 	",	
"	STELLA 	",	
"	SUBARU OTHER 	",	
"	TREZIA 	",	
"	VIVIO 	",	
"	WRX S4 	",	
"	WRX STI 	"	],
"DAIHATSU":	[		
"	ALTIS 	",	
"	ATRAI 	",	
"	ATRAI 7 	",	
"	ATRAI WAGON 	",	
"	BEGO 	",	
"	BOON 	",	
"	BOON LUMINAS 	",	
"	CAST 	",	
"	COO 	",	
"	COPEN 	",	
"	DELTA TRUCK 	",	
"	DELTA VAN 	",	
"	ESSE 	",	
"	HIJET CARGO 	",	
"	HIJET TRUCK 	",	
"	HIJET VAN 	",	
"	MAX 	",	
"	MIDGETII 	",	
"	MIRA 	",	
"	MIRA AVY 	",	
"	MIRA COCOA 	",	
"	MIRA CUSTOM 	",	
"	MIRA E:S 	",	
"	MIRA GINO 	",	
"	MIRA GINO 1000 	",	
"	MIRA TR-XX 	",	
"	MOVE 	",	
"	MOVE CANBUS 	",	
"	MOVE CONTE 	",	
"	MOVE LATTE 	",	
"	NAKED 	",	
"	OPTI 	",	
"	SONICA 	",	
"	TANTO 	",	
"	TANTO EXE 	",	
"	TERIOS 	",	
"	TERIOS KID 	",	
"	TERIOS LUCIA 	",	
"	THOR 	",	
"	WAKE 	",	
"	YRV 	"	],
"SUZUKI":	[		
"	AERIO 	",	
"	ALTO 	",	
"	ALTO ECO 	",	
"	ALTO LAPIN 	",	
"	ALTO LAPIN CHOCOLAT 	",	
"	ALTO TURBO RS 	",	
"	ALTO WORKS 	",	
"	BALENO 	",	
"	CAPPUCCINO 	",	
"	CARRY TRUCK 	",	
"	CERVO 	",	
"	CERVO CLASSIC 	",	
"	CHEVROLET CRUSE 	",	
"	CHEVROLET MW 	",	
"	CULTUS WAGON 	",	
"	ESCUDO 	",	
"	EVERY 	",	
"	EVERY LANDY 	",	
"	EVERY WAGON 	",	
"	GRAND ESCUDO 	",	
"	HUSTLER 	",	
"	IGNIS 	",	
"	JIMNY 	",	
"	JIMNY L 	",	
"	JIMNY SIERRA 	",	
"	JIMNY WIDE 	",	
"	KEI 	",	
"	KEI SPORT 	",	
"	KEI WORKS 	",	
"	LANDY 	",	
"	MIGHTY BOY 	",	
"	MR WAGON 	",	
"	MR WAGON WIT 	",	
"	PALETTE 	",	
"	PALETTE SW 	",	
"	SOLIO 	",	
"	SOLIO BANDIT 	",	
"	SPACIA 	",	
"	SPACIA CUSTOM 	",	
"	SPACIA CUSTOM Z 	",	
"	SPLASH 	",	
"	SWIFT 	",	
"	SWIFT SPORT 	",	
"	SX4 	",	
"	SX4 S CROSS 	",	
"	TWIN 	",	
"	WAGON R 	",	
"	WAGON R RR 	",	
"	WAGON R SOLIO 	",	
"	WAGON R STINGRAY 	"	],
"ISUZU":	[		
"	117 COUPE 	",	
"	BIGHORN 	",	
"	COMO 	",	
"	COMO MICROBUS 	",	
"	ELF TRUCK 	",	
"	FORWARD 	",	
"	FORWARD JUSTON 	",	
"	GEMINI 	",	
"	GIGA 	",	
"	ISUZU OTHER 	",	
"	ISUZU TRUCK 	",	
"	JOURNEY BUS 	",	
"	MU WIZARD 	"	],
"HINO":	[		
"	DUTRO 	",	
"	DUTRO HYBRID 	",	
"	HINO OTHER 	",	
"	HINO RAINBOW 	",	
"	HINO RANGER 	",	
"	HINO TRUCK 	",	
"	PROFIA 	",	
"	RIESSE 	",	
"	RIESSE II 	"	],
"MITSUOKA":	[		
"	GALUE 	",	
"	GALUE II 	",	
"	LE SEYDE 	",	
"	RAY 	",	
"	VIEWT 	"	],
"MITSUBISHI FUSO":	[		
"	CANTER 	",	
"	CANTER GUTS 	",	
"	FIGHTER 	",	
"	FIGHTER MIGNON 	",	
"	FUSO TRUCK 	",	
"	MITSUBISHI FUSO OTHER 	",	
"	ROSA 	",	
"	SUPER GREAT 	",	
"	THE GREAT 	"	],
"NISSAN DIESEL":	[		
"	BIG THUMB 	",	
"	CONDOR 	",	
"	NISSAN DIESEL OTHER 	",	
"	NISSAN UD 	",	
"	QUON 	"	]
};
///////////////////////////////////////////////




var list = 

[
"アイシス ",
"ウィッシュ ",
"ヴィッツ ",
"オーリス ",
"カローラアクシオ ",
"カローラフィールダー ",
"サクシード ",
"サクシードバン ",
"サクシードワゴン ",
"シエンタ ",
"パッソ ",
"プロボックス ",
"プロボックスバン ",
"プロボックスワゴン ",
"ベルタ ",
"ポルテ ",
"マークＸ ",
"ラウム ",
"ラクティス ",
"ＡＤ ",
"ＡＤエキスパート ",
"ＡＤバン ",
"ウイングロード ",
"セレナ ",
"ティーダラティオ ",
"ノート ",
"インサイト ",
"シビックハイブリッド ",
"ストリーム ",
"フィット ",
"アクセラ ",
"アクセラスポーツ ",
"デミオ ",
"インプレッサ "
	
];



var cars = $('input[name="CarCategoryNoOption"]'); 

cars.each(function()
{
	if (findCar($(this).parent().parent().text()))
	{
		$(this).prop("checked", true);
		
	}
	
	});
	
function findCar(c)
{
	for (var i=0;i<list.length;i++)
	{
		if (c.indexOf(list[i])>=0)
		{
			console.log(c);
			return true;
		}
	}
}

